
use std::{fs::File, io::{self, BufRead, BufReader}};

pub fn load_american_frequencies() -> Result<Vec<(String, f64)>, io::Error> {
  let topwords_path = "res/topwords.txt";

  BufReader::new(File::open(topwords_path)?).lines().skip(1).map(|line| {
    line.map(|line| {
      let tokens: Vec<&str> = line.split(" ").skip(1).take(2).collect();
    
      let word = tokens[0].to_owned();
      let freq_str = tokens[1];
    
      let frequency: i32 = freq_str.parse().unwrap();
      let frequency = frequency as f64;

      (word, frequency)
    })
  }).collect()
}


// Frequencies for words with apostrophes, which topwords.txt splits apart.
// Generated by scripts/contraction_frequencies.py, in topwords.txt's units.
pub fn load_contraction_frequencies() -> Result<Vec<(String, f64)>, io::Error> {
  let path = "res/contraction-frequencies.txt";

  BufReader::new(File::open(path)?).lines().map(|line| {
    line.map(|line| {
      let tokens: Vec<&str> = line.split(" ").collect();

      let word = tokens[0].to_owned();
      let frequency: i32 = tokens[1].parse().unwrap();

      (word, frequency as f64)
    })
  }).collect()
}
