#![allow(uncommon_codepoints, confusable_idents, mixed_script_confusables)]

pub mod dictionary;
pub mod glyphs;
pub mod frequencies;
pub mod sub_generation;
pub mod substitutions;
pub mod substitutions2;
pub mod hbshape;
pub mod fea_parsing;
pub mod hbshape_consistency_tests;
pub mod high_level_substitutions;
pub mod consensus_finding;
pub mod astarlike;
pub mod astarlike2;
pub mod gaussians;
pub mod gaussian_expectation_table;
pub mod gaussian_astarlike;
pub mod gaussian_expectation_table2;
pub mod gaussian_astarlike2;
pub mod gaussian_astarlike22;
pub mod high_level_substitutions2;
pub mod genastarlike;
pub mod pargenastarlike;
pub mod first_pass;
pub mod levenshtein;
pub mod half_rules;
pub mod lookups;
pub mod second_pass;
pub mod simple_substitutions;
pub mod readlex;
pub mod ipa;
pub mod american_frequencies;

